import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import Button from "react-bootstrap/Button";
import Card from "react-bootstrap/Card";
import Container from "react-bootstrap/Container";
import Form from "react-bootstrap/Form";
import Nav from "react-bootstrap/Nav";
import Navbar from "react-bootstrap/Navbar";
import Alert from "react-bootstrap/Alert";

export default function Home() {
  const [data, setData] = useState<{ a: number }>({ a: 0 });

  useEffect(() => {
    const getData = async () => {
      const res = await fetch("https://localhost:7255/homes");
      const data = res.json();
      return data;
    };
    getData().then((data) => setData(data));
  }, []);

  return (
    <>
      <Head>
        <title>Noti</title>
        <meta name="description" content="Generated by Noti" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Alert variant="danger" className="m-2">
        This is server response: {data.a} (actually 1), but CORS error
      </Alert>
      <Navbar expand="lg" bg="dark" variant="dark">
        <Container className="d-flex flex-row justify-around">
          <Navbar.Brand href="#home">
            <Image alt="" src="/favicon.ico" width="30" height="30" className="d-inline-block align-top" /> Noti
          </Navbar.Brand>
          <Form className="d-flex">
            <Form.Control type="search" placeholder="Search" className="me-2" aria-label="Search" />
            <Button variant="outline-success">Search</Button>
          </Form>
          <Navbar.Toggle />
          <Navbar.Collapse className="justify-content-end">
            <Nav className="">
              <Nav.Link href="#home">Signin</Nav.Link>
              <Nav.Link href="#link">Signup</Nav.Link>
              <Navbar.Text>
                Signed in as: <a href="#login">Mark Otto</a>
              </Navbar.Text>
              <Nav.Link href="#link">Logout</Nav.Link>
            </Nav>
          </Navbar.Collapse>
        </Container>
      </Navbar>
      <Container className="m-6 d-flex flex-row justify-between items-center">
        <Button variant="primary" className="">
          + new post
        </Button>
        <div className="d-flex flex-row ml-2 justify-between items-center lg:w-1/6">
          <span>Sort by: </span>
          <Form className="d-flex ml-2">
            <Form.Select aria-label="Default select example">
              <option value="1">Newest</option>
              <option value="2">Likes</option>
              <option value="3">Comments</option>
              <option value="4">Oldest</option>
            </Form.Select>
          </Form>
        </div>
      </Container>
      {[1, 2, 3, 4].map((i, _) => (
        <Container key={_} className="mt-4 ">
          <Card border="dark" className="my-2 hover:bg-gray-100 transition duration-300 bg">
            <Card.Header>Featured</Card.Header>
            <Card.Body>
              <Card.Title>Special title treatment {i}</Card.Title>
              <Card.Text>With supporting text below as a natural lead-in to additional content.</Card.Text>
              <Button variant="outline-danger">Like</Button>
            </Card.Body>
          </Card>
        </Container>
      ))}
    </>
  );
}
