import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Noti</title>
        <meta name="description" content="Generated by Noti" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>Hello, I am Next.</>
    </div>
  )
}

export default Home
